

/*================================================================
 *   
 *   
 *   文件名称：test_type.h
 *   创 建 者：肖飞
 *   创建日期：2022年06月01日 星期三 16时58分26秒
 *   修改日期：2022年08月03日 星期三 08时38分54秒
 *   描    述：
 *
 *================================================================*/
#ifndef _TEST_TYPE_H
#define _TEST_TYPE_H
#ifdef __cplusplus
extern "C"
{
#endif

#include "app_platform.h"
#include "cmsis_os.h"

typedef enum {
	TEST_TYPE_PORTS_NONE = 0,
	TEST_TYPE_PORTS_CONTACTOR_DRV,
	TEST_TYPE_PORTS_FAN1_RLY_DRV,
	TEST_TYPE_PORTS_VTRANS_1_12V_24,
	TEST_TYPE_PORTS_VTRANS_2_12V_24,
	TEST_TYPE_PORTS_BMSPOWER_PLUG1,
	TEST_TYPE_PORTS_BMSPOWER_PLUG2,
	TEST_TYPE_PORTS_LED_YELLOW_PLUG1,
	TEST_TYPE_PORTS_LED_YELLOW_PLUG2,
	TEST_TYPE_PORTS_LED_RED_PLUG1,
	TEST_TYPE_PORTS_LED_RED_PLUG2,
	TEST_TYPE_PORTS_LED_GREEN_POWER1,
	TEST_TYPE_PORTS_LED_GREEN_POWER2,
	TEST_TYPE_PORTS_CHARGING_LED_SCLK2,
	TEST_TYPE_PORTS_CHARGING_LED_LCLK2,
	TEST_TYPE_PORTS_CHARGING_LED_DS2,
	TEST_TYPE_PORTS_CHARGING_LED_SCLK1,
	TEST_TYPE_PORTS_CHARGING_LED_LCLK1,
	TEST_TYPE_PORTS_CHARGING_LED_DS1,
	TEST_TYPE_PORTS_PAR_EXT_TX1,
	TEST_TYPE_PORTS_PAR_EXT_TX2,
	TEST_TYPE_PORTS_PAR_EXT_TX3,
	TEST_TYPE_PORTS_PLUG1_LOCK_1,
	TEST_TYPE_PORTS_PLUG1_LOCK_2,
	TEST_TYPE_PORTS_PLUG2_LOCK_1,
	TEST_TYPE_PORTS_PLUG2_LOCK_2,
	TEST_TYPE_PORTS_DISCHARGE_RLY_PLUG1,
	TEST_TYPE_PORTS_DISCHARGE_RLY_PLUG2,
	TEST_TYPE_PORTS_MARQUEE1,
	TEST_TYPE_PORTS_MARQUEE2,
	TEST_TYPE_PORTS_MAIN_RLY_PLUG1,
	TEST_TYPE_PORTS_MAIN_RLY_PLUG2,
	TEST_TYPE_PORTS_BRG_RLY_DRV,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_1,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_2,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_3,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_4,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_5,


	TEST_TYPE_PORTS_DOOR1_OPEN,
	TEST_TYPE_PORTS_EPO,
	TEST_TYPE_PORTS_FUSE1_OPEN,
	TEST_TYPE_PORTS_FUSE2_OPEN,
	TEST_TYPE_PORTS_MAIN_RLY_PLUG1_BACK,
	TEST_TYPE_PORTS_MAIN_RLY_PLUG2_BACK,
	TEST_TYPE_PORTS_BRG_RLY_DRV_BACK,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_1_BACK,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_2_BACK,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_3_BACK,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_4_BACK,
	TEST_TYPE_PORTS_POWERDISTRIBUTION_5_BACK,
	TEST_TYPE_PORTS_FAN1_FAULT,
	TEST_TYPE_PORTS_FAN2_FAULT,
	TEST_TYPE_PORTS_FAN3_FAULT,
	TEST_TYPE_PORTS_FAN4_FAULT,
	TEST_TYPE_PORTS_FAN5_FAULT,
	TEST_TYPE_PORTS_PAR_EXT_RX1,
	TEST_TYPE_PORTS_PAR_EXT_RX2,
	TEST_TYPE_PORTS_PAR_EXT_RX3,
	TEST_TYPE_PORTS_PLUG1_LOCK_BACK,
	TEST_TYPE_PORTS_PLUG2_LOCK_BACK,
} test_type_t;

#ifdef __cplusplus
}
#endif
#endif //_TEST_TYPE_H
